x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '1.113.0'

  clusterConstraints:
    k8sVersion: ">=1.18.0"
    resources:
    - replicas: 2
      requests:
        cpu: 8
        memory: 8Gi

  publishedVersionMetadata:
    releaseNote: >-
      MostlyAI first GCP release.

  images:
    '':
      properties:
        repository:
          type: REGISTRY
        APP.image.name:
          type: REPO_WITHOUT_REGISTRY
        APP.image.tag:
          type: TAG

    app-ui:
      properties:
        repository:
          type: REGISTRY
        UI.image.name:
          type: REPO_WITHOUT_REGISTRY
        UI.image.tag:
          type: TAG

    ai-docs:
      properties:
        repository:
          type: REGISTRY
        UI.imageInit.name:
          type: REPO_WITHOUT_REGISTRY
        UI.imageInit.tag:
          type: TAG

    coordinator:
      properties:
        repository:
          type: REGISTRY
        CORDINATOR.image.name:
          type: REPO_WITHOUT_REGISTRY
        CORDINATOR.image.tag:
          type: TAG

    keycloak:
      properties:
        repository:
          type: REGISTRY
        KEYCLOAK.image.name:
          type: REPO_WITHOUT_REGISTRY
        KEYCLOAK.image.tag:
          type: TAG

    rabbitmq:
      properties:
        repository:
          type: REGISTRY
        RABBITMQ.image.name:
          type: REPO_WITHOUT_REGISTRY
        RABBITMQ.image.tag:
          type: TAG

    postgresql:
      properties:
        repository:
          type: REGISTRY
        PSQL.image.name:
          type: REPO_WITHOUT_REGISTRY
        PSQL.image.tag:
          type: TAG

    mostly-data:
      properties:
        repository:
          type: REGISTRY
        DATA.image.name:
          type: REPO_WITHOUT_REGISTRY
        DATA.image.tag:
          type: TAG

    mostly-engine-v2:
      properties:
        repository:
          type: REGISTRY
        CORDINATOR.envs.engine_image_name:
          type: REPO_WITHOUT_REGISTRY
        CORDINATOR.envs.engine_image_tag:
          type: TAG

    mostly-qa:
      properties:
        repository:
          type: REGISTRY
        CORDINATOR.envs.qa_image_name:
          type: REPO_WITHOUT_REGISTRY
        CORDINATOR.envs.engine_image_tag:
          type: TAG

    mostly-agent:
      properties:
        repository:
          type: REGISTRY
        CORDINATOR.envs.jobs_image_name:
          type: REPO_WITHOUT_REGISTRY
        CORDINATOR.envs.jobs_image_tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  domain:
    type: string
    title: The domain name
    default: mostlyai.company.com
    description: The fully qualified domain name of your app, for example mostlyai.company.com

required:
- name
- namespace
- domain
