apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.UI.name }}
  labels:
    app: {{ .Values.UI.name }}
spec:
  replicas: {{ .Values.UI.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.UI.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.UI.name }}
    spec:
      {{- if eq .Values.dedicatedAppNodes true }}
      {{- include "k8s.appNodes" . | nindent 6 }}
      {{- end }}
      {{- if eq .Values.platform "ocp" }}
      {{- include "ocp.securityContextTemplate" . | nindent 6 }}
      {{- end }}
      volumes:
        - name: mostly-docs
          emptyDir: {}
      initContainers:
        - name: mostly-docs
          image: {{ .Values.repository }}/{{ .Values.UI.imageInit.name }}:{{ .Values.UI.imageInit.tag }}
          {{- if eq .Values.platform "ocp" }}
          {{- include "ocp.securityContextContainer" . | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: mostly-docs
              mountPath: /www/docs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.imagePullPolicy }}
      containers:
        - name: {{ .Values.UI.name }}
          resources:
            {{- toYaml $.Values.UI.resources | nindent 12 }}
          image: {{ .Values.repository }}/{{ .Values.UI.image.name }}:{{ .Values.UI.image.tag }}
          {{- if eq .Values.platform "ocp" }}
          {{- include "ocp.securityContextContainer" . | nindent 10 }}
          {{- end }}
          ports:
            - name: {{ .Values.UI.ame }}
              containerPort: {{ .Values.UI.ports.containerPort }}
              protocol: TCP
          env:
            - name: ENV
              value: PROD
            {{- if .Values.LocalStorageInvisible }}
            - name: LOCAL_STORAGE_INVISIBLE
              value: '{{ .Values.LocalStorageInvisible }}'
            {{- end }}
            {{- if .Values.UI.GoogleTagManager }}
            - name: GOOGLE_TAG_MANAGER_ID
              value: {{ .Values.UI.GoogleTagManager.tag }}
            - name: GOOGLE_TAG_MANAGER_ENABLED
              value: '{{ .Values.GoogleTagManager.enabled }}'
            {{- end }}
          volumeMounts:
            - name: mostly-docs
              mountPath: /opt/app-root/src/docs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.imagePullPolicy }}
