apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.RABBITMQ.name }}
spec:
  ports:
    - name: {{ .Values.RABBITMQ.name }}
      protocol: TCP
      port: {{ .Values.RABBITMQ.ports.containerPort }}
      targetPort: {{ .Values.RABBITMQ.ports.containerPort }}
    - name: web-console
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
  selector:
    app: {{ .Values.RABBITMQ.name }}
