apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.CORDINATOR.name }}
  labels:
    app: {{ .Values.CORDINATOR.name }}
spec:
  replicas: {{ .Values.CORDINATOR.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.CORDINATOR.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.CORDINATOR.name }}
    spec:
      {{- if eq .Values.dedicatedAppNodes true }}
      {{- include "k8s.appNodes" . | nindent 6 }}
      {{- end }}
      {{- if eq .Values.platform "ocp" }}
      {{- include "ocp.securityContextTemplate" . | nindent 6 }}
      {{- end }}
      {{- if eq .Values.platform "k8s" }}
      {{- include "k8s.securityContextTemplate" . | nindent 6 }}
      {{- end }}
      volumes:
        - name: mostly-data
          persistentVolumeClaim:
            claimName: mostly-data
      containers:
        - name: {{ .Values.CORDINATOR.name }}
          resources:
            {{- toYaml $.Values.CORDINATOR.resources | nindent 12 }}
          image: {{ .Values.repository }}/{{ .Values.CORDINATOR.image.name }}:{{ .Values.CORDINATOR.image.tag }}
          {{- if eq .Values.platform "ocp" }}
          {{- include "ocp.securityContextContainer" . | nindent 10 }}
          {{- end }}
          {{- if eq .Values.platform "k8s" }}
          {{- include "k8s.securityContextContainer" . | nindent 10 }}
          {{- end }}
          {{- if eq .Values.platform "mac" }}
          {{- include "mac.securityContextContainer" . | nindent 10 }}
          {{- end }}
          ports:
            - name: mostly-cord
              containerPort: {{ .Values.CORDINATOR.ports.containerPort }}
              protocol: TCP
          env:
            - name: IS_OCP
              value: '{{ .Values.CORDINATOR.envs.is_ocp }}'
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.CORDINATOR.envs.coordinator_spring_profiles }}    
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_AGENT-RESOURCES_LIMITS_CPU
              value: {{ .Values.CORDINATOR.envs.jobs_resources.limits.agent_cpu }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_AGENT-RESOURCES_LIMITS_MEMORY
              value: {{ .Values.CORDINATOR.envs.jobs_resources.limits.agent_memory }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_AGENT-RESOURCES_REQUESTS_CPU
              value: {{ .Values.CORDINATOR.envs.jobs_resources.requests.agent_cpu }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_AGENT-RESOURCES_REQUESTS_MEMORY
              value: {{ .Values.CORDINATOR.envs.jobs_resources.requests.agent_memory }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_ENGINE-RESOURCES_LIMITS_CPU
              value: {{ .Values.CORDINATOR.envs.jobs_resources.limits.engine_cpu }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_ENGINE-RESOURCES_LIMITS_MEMORY
              value: {{ .Values.CORDINATOR.envs.jobs_resources.limits.engine_memory }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_ENGINE-RESOURCES_REQUESTS_CPU
              value: {{ .Values.CORDINATOR.envs.jobs_resources.requests.engine_cpu }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_ENGINE-RESOURCES_REQUESTS_MEMORY
              value: {{ .Values.CORDINATOR.envs.jobs_resources.requests.engine_memory }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.CORDINATOR.envs.coordinator_java_tool_options }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_NAMESPACE_COORDINATOR
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MOSTLY_AGENT_MAX-AGENTS
              value: '{{ .Values.CORDINATOR.envs.mostly_agent_max_agents }}'
            {{- if .Values.CORDINATOR.envs.run_as_user }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_JOB_RUN-AS-USER
              value: '{{ .Values.CORDINATOR.envs.run_as_user }}'
            {{- end }}
            {{- if .Values.CORDINATOR.envs.run_as_group }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_JOB_RUN-AS-GROUP
              value: '{{ .Values.CORDINATOR.envs.run_as_group }}'
            {{- end }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_JOB_NODE-LABEL-KEY
              value: '{{ .Values.CORDINATOR.envs.mostly_worker_label }}'
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_JOB_AGENT-ANNOTATIONS
              value: '{{ .Values.CORDINATOR.envs.agent_engine_annotation }}'
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_JOB_ENGINE-ANNOTATIONS
              value: '{{ .Values.CORDINATOR.envs.agent_engine_annotation }}'
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_IMAGE_REPOSITORY
              value: {{ .Values.repository }}/
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_IMAGE_TAG
              value: {{ .Values.CORDINATOR.envs.jobs_image_tag }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_IMAGE_ENGINE-TAG
              value: {{ .Values.CORDINATOR.envs.engine_image_tag }}
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_VOLUME_CLAIM
              value: mostly-data
            - name: MOSTLY_VM-POOL-MANAGEMENT_KUBERNETES_IMAGE_IMAGE-PULL-POLICY
              value: {{ .Values.imagePullPolicy }}
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgresql
                  key: mostly-coordinator-jdbc-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq
                  key: host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq
                  key: port
                  optional: true
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: password
            - name: JDK_JAVA_OPTIONS
              value: {{ .Values.CORDINATOR.envs.jdk_java_options }}
            - name: MOSTLY_STORAGE_CENTRAL-STORAGE-DIR-PATH
              value: /data
            - name: MOSTLY_STORAGE_LOCAL-STORAGE-DIR-PATH
              value: /data/local-storage
            - name: MOSTLY_VM-MANAGEMENT_VM-AUTOSTART-INTERVAL
              value: '1000'
          volumeMounts:
            - name: mostly-data
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.imagePullPolicy }}
      restartPolicy: Always
      serviceAccountName: mostly-coordinator
      serviceAccount: mostly-coordinator
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}

