---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mostly-coordinator
rules:
- verbs:
    - create
    - delete
    - deletecollection
    - patch
    - update
  apiGroups:
    - ''
  resources:
    - pods
    - pods/attach
    - pods/exec
    - persistentvolumeclaims
    - replicationcontrollers
    - replicationcontrollers/scale
- verbs:
    - create
    - delete
    - deletecollection
    - patch
    - update
  apiGroups:
    - batch
  resources:
    - jobs
- verbs:
    - get
    - list
    - watch
  apiGroups:
    - ''
  resources:
    - persistentvolumeclaims
    - persistentvolumeclaims/status
    - pods
    - pods/exec
    - pods/log
    - pods/status
    - replicationcontrollers
    - replicationcontrollers/scale
- verbs:
    - get
    - list
    - watch
  apiGroups:
    - batch
  resources:
    - jobs
    - jobs/status
  

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: mostly-coordinator
secrets:
{{- if .Values.imagePullSecrets }}
  - name: {{ .Values.imagePullSecrets }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecrets }}
{{- else }}
  - name: mostly-docker-cfg
imagePullSecrets:
  - name: mostly-docker-cfg
{{- end }}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mostly-coordinator
subjects:
  - kind: ServiceAccount
    name: mostly-coordinator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mostly-coordinator