{{- if .Values.route }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.KEYCLOAK.name }}
  annotations:
    {{- if .Values.route.annotations }}
    {{- toYaml $.Values.route.annotations | nindent 4 }}
    {{- end }}
spec:
  host: {{ .Values.route.fqdn }}
  path: /auth
  to:
    kind: Service
    name: {{ .Values.KEYCLOAK.name }}
    weight: 100
  port:
    targetPort: {{ .Values.KEYCLOAK.name }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}