apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.KEYCLOAK.name }}
type: Opaque
data:
  admin_client_secret: {{ .Values.KEYCLOAK.secrets.admin_client_secret }}
  admin_password: {{ .Values.KEYCLOAK.secrets.admin_password }}
  admin_username: {{ .Values.KEYCLOAK.secrets.admin_username }}
  api_client_secret: {{ .Values.KEYCLOAK.secrets.api_client_secret }}