apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
data:
  host: {{ .Values.PSQL.cm.host }}
  mostly-app: mostly-app
  mostly-app-jdbc-url: jdbc:postgresql://{{ .Values.PSQL.cm.host }}:{{ .Values.PSQL.cm.port }}/{{ .Values.PSQL.cm.mostly_app_db_name }}
  mostly-coordinator: mostly-coordinator
  mostly-coordinator-jdbc-url: jdbc:postgresql://{{ .Values.PSQL.cm.host }}:{{ .Values.PSQL.cm.port }}/{{ .Values.PSQL.cm.mostly_coordinator_db_name }}
  mostly-keycloak: mostly-keycloak
  mostly-keycloak-jdbc-url: jdbc:postgresql://{{ .Values.PSQL.cm.host }}:{{ .Values.PSQL.cm.port }}/{{ .Values.PSQL.cm.mostly_keycloak_db_name }}
  port: '{{ .Values.PSQL.cm.port }}'

{{- if eq .Values.PSQL.local_deployment true }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-provision
data:
  poststart.sh: |
    #!/bin/bash
    sleep 30s
    PGPASSWORD="$POSTGRESQL_POSTGRES_PASSWORD" psql -U postgres -c "CREATE DATABASE mostly_coordinator
        WITH
        OWNER = mostly
        ENCODING = 'UTF8'
        LC_COLLATE = 'en_US.UTF-8'
        LC_CTYPE = 'en_US.UTF-8'
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1;
        "

    PGPASSWORD="$POSTGRESQL_POSTGRES_PASSWORD" psql -U postgres -c "CREATE DATABASE mostly_keycloak
        WITH
        OWNER = mostly
        ENCODING = 'UTF8'
        LC_COLLATE = 'en_US.UTF-8'
        LC_CTYPE = 'en_US.UTF-8'
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1;
        "

    PGPASSWORD="$POSTGRESQL_POSTGRES_PASSWORD" psql -U postgres -c "CREATE DATABASE mostly_app
        WITH
        OWNER = mostly
        ENCODING = 'UTF8'
        LC_COLLATE = 'en_US.UTF-8'
        LC_CTYPE = 'en_US.UTF-8'
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1;
        "
    PGPASSWORD="$POSTGRESQL_POSTGRES_PASSWORD" psql -U postgres -c "grant all privileges on database mostly_coordinator to mostly;
    grant all privileges on database mostly_keycloak to mostly;
    grant all privileges on database mostly_app to mostly;
    grant all privileges on all tables in schema public to mostly;
    grant all privileges on all sequences in schema public to mostly;"

{{- end }}