{{- if eq .Values.PSQL.local_deployment true }}
---
kind: Secret
apiVersion: v1
metadata:
  name: mostly-db-secret
data:
  POSTGRESQL_POSTGRES_PASSWORD: {{ .Values.PSQL.secrets.psqlPostgresPass }}
  POSTGRESQL_DATABASE: {{ .Values.PSQL.secrets.psqlMostlyDatabase }}
  POSTGRESQL_PASSWORD: {{ .Values.PSQL.secrets.psqlMostlyPass }}
  POSTGRESQL_USERNAME: {{ .Values.PSQL.secrets.psqlMostlyUser }}
type: Opaque
{{- end }}

---
kind: Secret
apiVersion: v1
metadata:
  name: postgresql
data:
  username: {{ .Values.PSQL.secrets.psqlMostlyUser }}
  password: {{ .Values.PSQL.secrets.psqlMostlyPass }}
type: Opaque