{{- if .Values.certManager.enabled -}}
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.nginx.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-admission
  namespace: {{ .Values.nginx.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.nginx.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - {{ .Values.nginx.name }}-leader
  resources:
  - leases
  verbs:
  - get
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-admission
  namespace: {{ .Values.nginx.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - secrets
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-admission
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.nginx.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.nginx.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.nginx.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-admission
  namespace: {{ .Values.nginx.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.nginx.name }}-admission
subjects:
- kind: ServiceAccount
  name: {{ .Values.nginx.name }}-admission
  namespace: {{ .Values.nginx.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.nginx.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.nginx.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.nginx.name }}-admission
subjects:
- kind: ServiceAccount
  name: {{ .Values.nginx.name }}-admission
  namespace: {{ .Values.nginx.namespace }}
---
apiVersion: v1
data:
  allow-snippet-annotations: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-controller
  namespace: {{ .Values.nginx.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-controller
  namespace: {{ .Values.nginx.namespace }}
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-controller-admission
  namespace: {{ .Values.nginx.namespace }}
spec:
  ports:
  - appProtocol: https
    name: https-webhook
    port: 443
    targetPort: webhook
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-controller
  namespace: {{ .Values.nginx.namespace }}
spec:
  minReadySeconds: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: {{ .Values.nginx.name }}
      app.kubernetes.io/name: {{ .Values.nginx.name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: {{ .Values.nginx.name }}
        app.kubernetes.io/name: {{ .Values.nginx.name }}
        app.kubernetes.io/part-of: {{ .Values.nginx.name }}
        app.kubernetes.io/version: {{ .Values.nginx.appversion }}
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --publish-service=$(POD_NAMESPACE)/{{ .Values.nginx.name }}-controller
        - --election-id={{ .Values.nginx.name }}-leader
        - --controller-class=k8s.io/{{ .Values.nginx.name }}
        - --ingress-class=nginx
        - --configmap=$(POD_NAMESPACE)/{{ .Values.nginx.name }}-controller
        - --validating-webhook=:8443
        - --validating-webhook-certificate=/usr/local/certificates/cert
        - --validating-webhook-key=/usr/local/certificates/key
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LD_PRELOAD
          value: /usr/local/lib/libmimalloc.so
        image: {{ .Values.repository }}/{{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /wait-shutdown
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 8443
          name: webhook
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 90Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsUser: 101
        volumeMounts:
        - mountPath: /usr/local/certificates/
          name: webhook-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: {{ .Values.nginx.name }}
      terminationGracePeriodSeconds: 300
      volumes:
      - name: webhook-cert
        secret:
          secretName: {{ .Values.nginx.name }}-admission
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-admission-create
  namespace: {{ .Values.nginx.namespace }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admission-webhook
        app.kubernetes.io/instance: {{ .Values.nginx.name }}
        app.kubernetes.io/name: {{ .Values.nginx.name }}
        app.kubernetes.io/part-of: {{ .Values.nginx.name }}
        app.kubernetes.io/version: {{ .Values.nginx.appversion }}
      name: {{ .Values.nginx.name }}-admission-create
    spec:
      containers:
      - args:
        - create
        - --host={{ .Values.nginx.name }}-controller-admission,{{ .Values.nginx.name }}-controller-admission.$(POD_NAMESPACE).svc
        - --namespace=$(POD_NAMESPACE)
        - --secret-name={{ .Values.nginx.name }}-admission
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.k8s.io/{{ .Values.nginx.name }}/kube-webhook-certgen:{{ .Values.nginx.kube_webhook_certgen_tag }}
        imagePullPolicy: IfNotPresent
        name: create
        securityContext:
          allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: {{ .Values.nginx.name }}-admission
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-admission-patch
  namespace: {{ .Values.nginx.namespace }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admission-webhook
        app.kubernetes.io/instance: {{ .Values.nginx.name }}
        app.kubernetes.io/name: {{ .Values.nginx.name }}
        app.kubernetes.io/part-of: {{ .Values.nginx.name }}
        app.kubernetes.io/version: {{ .Values.nginx.appversion }}
      name: {{ .Values.nginx.name }}-admission-patch
    spec:
      containers:
      - args:
        - patch
        - --webhook-name={{ .Values.nginx.name }}-admission
        - --namespace=$(POD_NAMESPACE)
        - --patch-mutating=false
        - --secret-name={{ .Values.nginx.name }}-admission
        - --patch-failure-policy=Fail
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.k8s.io/{{ .Values.nginx.name }}/kube-webhook-certgen:{{ .Values.nginx.kube_webhook_certgen_tag }}
        imagePullPolicy: IfNotPresent
        name: patch
        securityContext:
          allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: {{ .Values.nginx.name }}-admission
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: nginx
spec:
  controller: k8s.io/{{ .Values.nginx.name }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Values.nginx.name }}
    app.kubernetes.io/version: {{ .Values.nginx.appversion }}
  name: {{ .Values.nginx.name }}-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.nginx.name }}-controller-admission
      namespace: {{ .Values.nginx.namespace }}
      path: /networking/v1/ingresses
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate.nginx.ingress.kubernetes.io
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
{{- end }}
